package com.lavi.tablearrangments.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class EventAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertEventAllPropertiesEquals(Event expected, Event actual) {
        assertEventAutoGeneratedPropertiesEquals(expected, actual);
        assertEventAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertEventAllUpdatablePropertiesEquals(Event expected, Event actual) {
        assertEventUpdatableFieldsEquals(expected, actual);
        assertEventUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertEventAutoGeneratedPropertiesEquals(Event expected, Event actual) {
        assertThat(actual)
            .as("Verify Event auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertEventUpdatableFieldsEquals(Event expected, Event actual) {
        assertThat(actual)
            .as("Verify Event relevant properties")
            .satisfies(a -> assertThat(a.getEventName()).as("check eventName").isEqualTo(expected.getEventName()))
            .satisfies(a -> assertThat(a.getEventOwners()).as("check eventOwners").isEqualTo(expected.getEventOwners()))
            .satisfies(a -> assertThat(a.getGroomParents()).as("check groomParents").isEqualTo(expected.getGroomParents()))
            .satisfies(a -> assertThat(a.getBrideParents()).as("check brideParents").isEqualTo(expected.getBrideParents()))
            .satisfies(a -> assertThat(a.getWeddingDate()).as("check weddingDate").isEqualTo(expected.getWeddingDate()))
            .satisfies(a -> assertThat(a.getReceptionTime()).as("check receptionTime").isEqualTo(expected.getReceptionTime()))
            .satisfies(a -> assertThat(a.getWeddingTime()).as("check weddingTime").isEqualTo(expected.getWeddingTime()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertEventUpdatableRelationshipsEquals(Event expected, Event actual) {
        // empty method
    }
}
